### ISSUE TITLE
Consider Adding Proxy Settings?

### ISSUE THREAD

**Issue by MatrixA** [dineshpinto/geckoterminal-api#1]
Have you considered add a optional proxy setting when initialize the gt. I think it may help some users who are overwhelming their privacy.

**Comment by dineshpinto** [comment]
Proxy support for the synchronous and async APIs is added in the latest commit (a20e4dd), usage is specified in the [README](https://github.com/dineshpinto/geckoterminal-api?tab=readme-ov-file#proxy-support).

**Comment by taylorcammack** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ktmlm, @asynctomatic, @2020-io, @alex-fang, @zeusAlgo, @kss-fluency, @HussainMehdi, @piavgh, @m2m-architect, @jakerumbles, @edmand46, @Phonbopit, @hexrcs, @dec0dOS, @BlockchainWatchDog, @vaniisgh, @djtech-dev, @arthurmm-cloudwalk, @bmwoolf, @megared05, @ngmisl, @rhnparlors, @fwx5618177, @madnight, @tgcfae999, @yihau, @odyssey2077, @EthSecurity1, @denismaxim0v, @mia-stein, @oantoro, @j0rGeT, @kirubarajan, @yourmoonlight, @hhamud, @mattgstevens, @billylindeman, @qymlyl, @yaroslavyaroslav, @zqhxuyuan, @vyorkin, @Volland, @martinloesethjensen, @ThomasMarches, @weipin, @winary, @liwei1997, @lightning-li, @goalongway, @jjttjjcrossle, @trsmarc, @ray1888, @bejitono, @51t1n74k, @taye-beckford, @wenxingxing, @GrandGarcon, @odyzzey, @carlynf, @junhoyeo, @kirubarajan, @Alex180299, @0xAdil, @0xMMBD, @evmcheb, @Yuan-ManX, @dannysun85, @arman324, @misoobu, @2020-io, @insipx, @AlexKaravaev, @code0xff, @Z-Zhijie, @sorawit, @triplebeamdream, @Fatihkts, @kekonen, @en, @stephenwalker2020, @shiyivei, @wdv4758h, @Ay-355, @inigogb, @nmoroze, @stormcoder, @artjoma, @mojtaba-eshghie, @kadenzipfel, @skvorn, @bredamatt, @ZhangHanDong, @myiwen, @AwesomeObserver, @dzmitry-lahoda, @astrolemonade, @Phonbopit, @lancejpollard, @thasaritolet4be, @elpiel, @SlickZhang, @refcell, @daweth, @estebgonza, @xiumiao, @xcshuan, @saadjhk, @franssl, @rahulnm, @DaviRain-Su, @ThomasMarches, @j75689, @b00f, @3b40eb98, @lmatz, @stechu, @lemonps, @nilslice, @theophoric, @bolak, @ever0de, @tzxyz, @cluo, @Dreamerryao, @velihdzen, @anajuliabit, @xbhuang1994, @nyuta01, @zkmsg, @songtianyi, @cmars, @lightclient, @lsuanet, @typistv, @djtech-dev, @docongminh, @Eikix, @1997roylee, @nanjingboy, @citizen-stig, @Troublor, @asynctomatic, @ciaobotta, @omegablitz, @uniyalabhishek, @metricsazxc, @zhubby, @mulfdev

**Comment by felixovelar** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
cyberpunk256, @michmcc, @antoinegelloz, @bohendo, @fire17, @keinsell, @AppServiceProvider, @jasonpearce, @Faustino-CIMA, @nyudenkov, @ygunayer, @hehpollon, @YHTerrance, @alancwoo, @jaredwolff, @rakanalh, @Prashant-Chaurasia, @bobkilla, @vijaykrishnavanshi, @tonven, @colbyg333, @Liemeister, @jemacom, @MrSaints, @keyneszeng, @lodorg, @PiotrPiesiak, @afurculita, @0xmsu, @brizzbane, @jzstern, @ScMofeoluwa, @johnnyfox87, @infloop, @zfsamzfsam, @FranciscoArredondo, @scootcho, @efontan, @juergenhoetzel, @aaronmboyd, @jimsjoh, @PedroGalveias, @sbellem, @yuopu0285, @0xhaile, @tcosnr, @cauta, @Joshuaeggon, @jb99x, @fmendes409H, @nicobao, @ches, @bsormagec, @nono2357, @bjackson, @dufour-yohann, @monkfoot, @enockzaake, @mykeels, @choudhary, @iamgenchi, @Dunnomix, @nikolay, @bugatsinho, @nikita-popov, @Wheaties466, @marioevz, @githubber, @kalyberk, @AmanSingh81757, @gilescope, @geet-eth, @Garandor, @dckc, @wimmeldj, @Anastasios-skg, @happysammy, @elranu, @superatomic, @tugytur, @srcnix, @Zorro909, @fpgaq, @jojanaho, @person-m, @shredEngineer, @jonathan-s, @ysy970923, @lukemulks, @mstattma, @StephenMilone, @abra, @tibkiss, @kyodhin, @Sandesh333333, @pauloedurezende, @liurui2014, @bonedaddy, @lyoshenkadec0dOS, @1H0, @0xtaos, @canesin, @murielsilveira, @xuhdev, @vkatushenok, @Mansarde, @johnkferguson, @Guillerbr, @valer-cara, @findtoni, @zolotokrylin, @bitcoinwarrior1, @jldevezas, @jimsjoh, @aeaeae69, @cyborgshead, @rcstanciu, @chengguizi, @devnulled, @funkle34, @sorokinvld, @Thaone027, @benjlevesque, @EricCrosson, @wmitsuda, @furqanrydhan, @dnivi3, @hehpollon, @eduardomoroni, @throughnothing, @Desgard, @thezillia, @Zoinzibar, @synagonism, @leNicDev, @bobkilla, @nyimbi, @Sea-Wolfe, @bkonzman, @dmxify, @dario-locci, @clouedoc, @arall, @NirShakibi, @xplosionmind, @ajays97, @karvounis, @vlnk
